version: 2
updates:
  - package-ecosystem: cargo
    directory: "extensions/dynops"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
