version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    groups:
      all:
        patterns: ['*']
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
