version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      cargo:
        applies-to: version-updates
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
