version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      rust:
        patterns:
          - "*"
        update-types:
          - major
          - minor
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
