name = "Dynamic Operations"
prefix = "dynops"
modname = "dynops"
author = "DarkWanderer"
files = [
    "*.dll",
    "*.so",
    "README.md",
    "LICENSE",
    "mod.cpp",
    "meta.cpp"
]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip dynops_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

show_output = true