name = "Dynamic Operations"
prefix = "dynops"
author = "DarkWanderer"
files = [
    "*.dll",
    "*.so",
    "README.md",
    "LICENSE",
    "mod.cpp",
    "meta.cpp"
]

keyname = "{{prefix}}_{{version}}"
signame = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip dynops_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

[header_exts]
version = "0.1.0-{{git \"id 8\"}}"