name = "Dynamic Operations"
prefix = "dynops"
modname = "dynops"
author = "DarkWanderer"

[files]
include = [
    "*.dll",
    "*.so",
    "README.md",
]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip dynops_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

show_output = true
