name = "Dynamic Operations"
prefix = "dynops"
modname = "dynops"
mainprefix = "dw"

[properties]
author = "Kozak"
url = "https://github.com/DarkWanderer/DynamicOperations"

[files]
include = ["*.dll", "*.so", "README.md"]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip dynops_{{semver.major}}.{{semver.minor}}.{{semver.patch}}",
]

show_output = true

[hemtt.launch.default]
workshop = [
    "450814997", # CBA_A3's Workshop ID
]
parameters = [
    "-skipIntro",
    "-noSplash",
    "-showScriptErrors",
    "-debug",
    "-filePatching",
    "mpmissions\\MP_DynOps_ChatTest.Enoch\\mission.sqm",
]
