name: Build

on:
  push:
    branches:
    - master

jobs:
  lint:
    name: SQFLint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: SQFLint
      uses: arma-actions/sqflint@master
      continue-on-error: true # No failure due to many false-positives:
 
  build-extension-windows-x64:
    name: Build extension (Windows x64)
    runs-on: windows-latest
    steps:
      - uses: Swatinem/rust-cache@v1

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
          
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Test
        working-directory: extensions/dynops
        run: cargo test
      
      - name: Build release
        working-directory: extensions/dynops
        run: |
          cargo build --release
          move target/release/dynops.dll ../../dynops_x64.dll
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: extension-x64-windows
          path: dynops_x64.dll

  build-extension-linux-x64:
    name: Build extension (Linux x64)
    runs-on: ubuntu-latest
    steps:
      - uses: Swatinem/rust-cache@v1

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
          
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Test
        working-directory: extensions/dynops
        run: cargo test
      
      - name: Build release
        working-directory: extensions/dynops
        run: |
          cargo build --release
          mv target/release/libdynops.so ../../dynops_x64.so
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: extension-x64-linux
          path: dynops_x64.so

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
     - build-extension-windows-x64
     - build-extension-linux-x64
    steps:     
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Download Windows x64
      uses: actions/download-artifact@v2
      with:
        name: extension-x64-windows
        path: .

    - name: Download Linux x64
      uses: actions/download-artifact@v2
      with:
        name: extension-x64-linux
        path: .
    
    - name: Build using HEMTT
      uses: arma-actions/hemtt@master
      with:
        command: build --release --ci
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2-preview
      with:
        name: dynops-${{ github.sha }}-nobin
        path: releases/dynops_*.zip
