name: Clippy Fix

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

jobs:
  rust-clippy-fix:
    name: Fix
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true

      - name: Init Cargo cache
        uses: Swatinem/rust-cache@v2

#      - name: Install required cargo
#        run: cargo install clippy-sarif sarif-fmt

      - name: Run rust-clippy
        run:
          cargo clippy --fix

      - name: pull-request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: '[Clippy] Cargo Fix suggestions',
              owner,
              repo,
              head: '${{ github.ref_name }}',
              base: 'master',
              body: 'This PR is auto-generated by\n[actions/github-script](https://github.com/actions/github-script).'
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['rust', 'clippy']
            });
