name: Clippy Fix

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

jobs:
  rust-clippy-fix:
    name: Fix
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true

      - name: Init Cargo cache
        uses: Swatinem/rust-cache@v2

      - name: clippy-fix
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --fix
                    
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with: 
          commit-message: "Automated fixes by Clippy"
          delete-branch: true
          title: "[clippy] Suggested Clippy fixes"
          labels: "rust,clippy"
