name: Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '17 3 * * 1'

jobs:
  build:
    name: Build
    uses: ./.github/workflows/reusable-build.yml
    
  virustotal:
    name: VirusTotal Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    needs: build

    steps:
      - name: Download Windows x64
        uses: actions/download-artifact@v4
        with:
          name: extension-x64-windows
          path: .
  
      - name: Download Linux x64
        uses: actions/download-artifact@v4
        with:
          name: extension-x64-linux
          path: .
          
      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VIRUSTOTAL_APIKEY }}
          request_rate: 4
          files: |
            ./dynops_x64.dll
            ./dynops_x64.so

  pre-release:
    name: Publish pre-release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    steps:
    - name: Download Addon
      uses: actions/download-artifact@v4
      with:
        name: DynamicOperations
        path: .
        
    - name: Push pre-release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development build"
        files: dynops-latest.zip
