name: Build

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
    paths-ignore:
    - README.md
    - .git*

jobs:
  build:
    name: Build
    uses: ./.github/workflows/reusable-build.yml
