name: PR

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
    paths-ignore:
    - README.md
    - .git*

jobs:
  build:
    name: Build
    uses: ./.github/workflows/reusable-build.yml
    
  lint:
    name: SQFLint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Enable problem matcher
      run: echo "::add-matcher::.github/matchers/sqf.json"
    
    - name: SQFLint
      uses: arma-actions/sqflint@master
      continue-on-error: true # No failure due to many false-positives:

  parse:
    name: Run SQF parse test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
          
    - name: SQLVM parse test
      uses: darkwanderer/sqfvm-action@master
      continue-on-error: true # No failure, experimental run
      with:
        command: --input-sqf addons/factions/fnc_initFactions.sqf
